name: Validate Code

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Roundtrip Test
        run: |
          python -m tests.test_roundtrip